on:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\psf-prerequisites.ps1
      shell: powershell
    - name: Install Prerequisites
      run: .\build\vsts-help.ps1
      shell: powershell
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
      shell: powershell
      env:
        APIKEY: ${{ secrets.ApiKey }}
    - name: Release
      run: .\build\vsts-release.ps1
      shell: powershell
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}